#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 700
#define MAX_LINES 50
#define LINE_HEIGHT 35
#define MAX_PAGE_TEXT_SIZE 500
#define PAGE_THICKNESS 1
#define PAGE_GAP 1
#define PAGE_HEIGHT 300
#define PAGE_WIDTH 300
#define PAGE_TYPE_TEXT 0
#define PAGE_TYPE_DRAWING 1
#define BOOK_THICKNESS 20
#define BOOK_BORDER_SIZE 20
#define BOOK_HEIGHT PAGE_HEIGHT + 2*BOOK_BORDER_SIZE
#define BOOK_WIDTH PAGE_WIDTH + 2*BOOK_BORDER_SIZE
#define MAX_NO_PAGES 100
#define MARGIN_HEIGHT 30
#define MARGIN_WIDTH 30
#define WALL_THICKNESS 50
#define WALL_HEIGHT 500
#define WALL_WIDTH 500
#define PAGE_FLIP_SPEED 2